---
- name: Install Docker
  hosts: localhost
  become: true

  vars:
    tmp_key_location: /tmp/docker.gpg
    key_location: /usr/share/keyrings/docker.gpg

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install prerequisites for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Retrieve system environment
      block:
        - name: Get the username running the deploy
          become: false
          register: host_username
          changed_when: host_username.rc != 0
          ansible.builtin.command: whoami

        - name: Display Command Output
          ansible.builtin.debug:
            var: host_username.stdout

        - name: Get System Architecture
          register: get_system_arch
          changed_when: get_system_arch.rc != 0
          ansible.builtin.command: dpkg --print-architecture

        - name: Display Command Output
          ansible.builtin.debug:
            var: get_system_arch.stdout

        - name: Get Version Code Name
          register: get_version_codename
          changed_when: get_version_codename.rc != 0
          ansible.builtin.shell: |
            source /etc/os-release &&\
            echo $VERSION_CODENAME
          args:
            executable: /bin/bash

        - name: Display Command Output
          ansible.builtin.debug:
            var: get_version_codename.stdout

    - name: One way to avoid apt_key once it is removed from your distro
      block:
        - name: Download GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/debian/gpg
            dest: "{{ tmp_key_location }}"
            mode: "0444"

        - name: Install GPG Key
          register: apt_key
          changed_when: apt_key.rc != 0
          ansible.builtin.shell: |
            cat {{ tmp_key_location }} | gpg --batch --yes --dearmor --quiet -o {{ key_location }}
          args:
            executable: /bin/bash

        - name: Update file permission
          ansible.builtin.file:
            path: "{{ key_location }}"
            mode: "0444"

        - name: Remove tmp file
          ansible.builtin.file:
            path: "{{ tmp_key_location }}"
            state: absent

        - name: Attempt
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by={{ key_location }}] https://download.docker.com/linux/debian {{ get_version_codename.stdout }} stable"
            state: present
            filename: docker.list

    - name: Install Docker package
      block:
        - name: Update APT package cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install Docker
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

    - name: Docker Post Install
      block:
        - name: Add the user to the docker group
          ansible.builtin.user:
            name: "{{ host_username.stdout }}"
            groups: docker
            append: true
          become: true

        - name: Start Docker service
          ansible.builtin.service:
            name: docker
            state: started
            enabled: true
