- name: Docker Installation
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python

  roles:
    - role: rhattox.apt_repo_install.gpg
      vars:
        root_app_url: https://download.docker.com/linux/debian
        key_final_destination: "{{ keyring_path }}/docker.asc"
        ourcelist_destination: "{{ source_list_path }}/docker.list"
        sourcelist_content: "deb [arch=amd64 signed-by={{ key_final_destination }}] {{ root_app_url }} {{ ansible_distribution_release }} stable"
    - role: docker
