- name: Update Packages And Add Required Packages
  block:
  - name: Update APT package cache
    ansible.builtin.apt:
      update_cache: true

  - name: Install Packages
    ansible.builtin.apt:
      name: "{{ core_packages | from_yaml }}"
      state: present
