- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install prerequisites for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: Download GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg
        dest: "{{ tmp_key_location }}"
        mode: "640"

    - name: Install GPG Key
      register: apt_key
      changed_when: apt_key.rc != 0
      ansible.builtin.shell: |
        cat {{ tmp_key_location }} | gpg --batch --yes --dearmor --quiet -o {{ key_location }}
      args:
        executable: /bin/bash

    - name: Update file permission
      ansible.builtin.file:
        path: "{{ key_location }}"
        mode: "640"

    - name: Remove tmp file
      ansible.builtin.file:
        path: "{{ tmp_key_location }}"
        state: absent

    - name: Install APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by={{ key_location }}] https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release }} stable"
        state: present
        filename: docker.list

- name: Install Docker package
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

- name: Docker Post Install
  block:
    - name: Add the user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: docker
        append: true
      become: true

    - name: Update Docker Service
      ansible.builtin.template:
        src: "roles/docker/templates/docker.service.j2"
        dest: "/usr/lib/systemd/system/docker.service"
        owner: root
        group: root
        mode: "0640"

    - name: Add Docker DNS
      ansible.builtin.template:
        src: "roles/docker/templates/daemon.json.j2"
        dest: "/etc/docker/daemon.json"
        owner: root
        group: root
        mode: "0640"

    - name: Enable Service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start Service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
