- name: Post Install
  block:
    - name: Add User To App Group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: "{{ app_name }}"
        append: true

    - name: Enable Service
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start Service
      become: true
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: started
        enabled: true
